/* ============================================================
   Pass 8 — trial-conduct features
   ------------------------------------------------------------
   Exports MULTIPLE Express routers (same pattern as pass7.js):

     1. randomizationRouter  /api/randomization
        Permuted-block (optionally stratified) randomization.
        Deterministic: arm derived from (seed, stratum, block_no),
        so the schedule is reproducible + auditable without
        storing pre-generated lists.
     2. sdtmRouter           /api/sdtm
        Read-only SDTM-shaped export of DM / AE / DV domains from
        existing tables (JSON or CSV). SDTM-SHAPED, not validated
        against CDISC conformance rules.
     3. dsmbRouter           /api/dsmb
        DSMB packet: cross-table safety/enrollment aggregation +
        ADVISORY-ONLY AI executive summary.
     4. forecastRouter       /api/enrollment-forecast
        Deterministic accrual projection + AI narrative.
     5. aiRouter             /api/ai (extends surface)
        meddra-code (ADVISORY — NOT licensed MedDRA), and
        safety-narrative (ADVISORY).
     6. form1572Router       /api/form-1572
        Deterministic DRAFT Form FDA 1572 assembly from
        investigators + sites + trials.
     7. delegationRouter     /api/delegation-log      (CRUD)
     8. trainingRouter       /api/training-records    (CRUD)

   Persistence: every AI POST writes to ai_results(feature,input,output,model).
   ============================================================ */

const express = require('express');
const pool = require('../config/database');
const { callOpenRouter, safeJsonParse } = require('../services/ai');

const MODEL = process.env.OPENROUTER_MODEL || 'anthropic/claude-haiku-4.5';
const SYSTEM_PROMPT = 'You are an expert clinical trial methodologist, biostatistician, and pharmaceutical R&D advisor. Provide rigorous, evidence-based, regulator-aware recommendations grounded in ICH-GCP, FDA, and EMA guidance. Always return STRICT JSON when a schema is given.';

const ADVISORY_DISCLAIMER =
  'ADVISORY OUTPUT ONLY. This response is generated by a language model and is NOT validated for regulatory submission, ' +
  'patient-care decisions, or go/no-go program decisions. It MUST be independently reviewed by a qualified biostatistician, ' +
  'medical monitor, regulatory affairs professional, or other domain expert before any operational use.';

function withAdvisory(obj) {
  return {
    disclaimer: ADVISORY_DISCLAIMER,
    requires_expert_review: true,
    not_for_regulatory_submission: true,
    ...obj,
  };
}

async function persist(feature, input, output) {
  try {
    await pool.query(
      'INSERT INTO ai_results (feature, input, output, model) VALUES ($1,$2,$3,$4)',
      [feature, input, output, MODEL]
    );
  } catch (e) {
    console.warn('[ai_results] persist warning:', e.message);
  }
}

function csvEscape(v) {
  if (v === null || v === undefined) return '';
  const s = String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function toCsv(rows, cols) {
  const head = cols.join(',');
  const body = rows.map(r => cols.map(c => csvEscape(r[c])).join(',')).join('\n');
  return head + '\n' + body + '\n';
}

/* ============================================================
   ROUTER 1 — Randomization / IWRS  (/api/randomization)
   ============================================================ */

// Deterministic 32-bit PRNG (mulberry32) seeded from a string hash,
// so block shuffles are reproducible from (scheme.seed, stratum, block_no).
function hashString(s) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Build the (deterministic) permuted block for a given block number.
// The block contains each arm repeated proportionally to its ratio,
// scaled to block_size, then Fisher-Yates shuffled with the seeded PRNG.
function permutedBlock(scheme, stratum, blockNo) {
  const arms = scheme.arms;
  const ratioSum = arms.reduce((s, a) => s + (a.ratio || 1), 0);
  const perUnit = Math.max(1, Math.floor(scheme.block_size / ratioSum));
  const block = [];
  for (const a of arms) for (let i = 0; i < (a.ratio || 1) * perUnit; i++) block.push(a.name);
  const rand = mulberry32(hashString(`${scheme.seed}|${stratum}|${blockNo}`));
  for (let i = block.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [block[i], block[j]] = [block[j], block[i]];
  }
  return block;
}

const randomizationRouter = express.Router();

randomizationRouter.get('/schemes', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM randomization_schemes ORDER BY id DESC');
    res.json(r.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

randomizationRouter.get('/irt/kits', async (req, res) => {
  try {
    const { trial, site, status } = req.query;
    const where = [];
    const params = [];
    let i = 1;
    if (trial) { where.push(`trial=$${i++}`); params.push(trial); }
    if (site) { where.push(`site=$${i++}`); params.push(site); }
    if (status) { where.push(`status=$${i++}`); params.push(status); }
    const sql = `SELECT * FROM irt_kits ${where.length ? `WHERE ${where.join(' AND ')}` : ''} ORDER BY trial, site, arm, kit_id`;
    const r = await pool.query(sql, params);
    res.json(r.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

randomizationRouter.get('/irt/dispenses', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM irt_dispenses ORDER BY dispensed_at DESC, id DESC LIMIT 200');
    res.json(r.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

randomizationRouter.post('/schemes', async (req, res) => {
  try {
    const { scheme_id, trial, block_size, arms, strata, category_schema, seed } = req.body;
    if (!scheme_id) return res.status(400).json({ error: 'scheme_id is required' });
    const armList = Array.isArray(arms) && arms.length >= 2 ? arms : [{ name: 'Active', ratio: 1 }, { name: 'Placebo', ratio: 1 }];
    const ratioSum = armList.reduce((s, a) => s + (a.ratio || 1), 0);
    const bs = Number(block_size) || ratioSum * 2;
    if (bs % ratioSum !== 0) {
      return res.status(400).json({ error: `block_size (${bs}) must be a multiple of the allocation-ratio sum (${ratioSum})` });
    }
    const r = await pool.query(
      `INSERT INTO randomization_schemes (scheme_id, trial, method, block_size, arms, strata, category_schema, seed)
       VALUES ($1,$2,'permuted-block',$3,$4,$5,$6,$7) RETURNING *`,
      [scheme_id, trial || null, bs, JSON.stringify(armList),
       JSON.stringify(Array.isArray(strata) ? strata : []),
       JSON.stringify(Array.isArray(category_schema) ? category_schema : []),
       seed || `${scheme_id}-${Date.now()}`]
    );
    res.status(201).json(r.rows[0]);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

randomizationRouter.get('/schemes/:schemeId', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM randomization_schemes WHERE scheme_id=$1', [req.params.schemeId]);
    if (r.rows.length === 0) return res.status(404).json({ error: 'Scheme not found' });
    const a = await pool.query(
      'SELECT * FROM randomization_assignments WHERE scheme=$1 ORDER BY stratum, block_no, position',
      [req.params.schemeId]
    );
    res.json({ ...r.rows[0], assignments: a.rows });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// Randomize one subject. Position within stratum decides block number and
// slot; the block itself is regenerated deterministically — nothing secret
// is stored, and the full schedule can be re-derived for audit.
randomizationRouter.post('/schemes/:schemeId/assign', async (req, res) => {
  const client = await pool.connect();
  try {
    const { subject_id, stratum } = req.body;
    if (!subject_id) return res.status(400).json({ error: 'subject_id is required' });
    await client.query('BEGIN');
    const s = await client.query('SELECT * FROM randomization_schemes WHERE scheme_id=$1 FOR UPDATE', [req.params.schemeId]);
    if (s.rows.length === 0) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'Scheme not found' }); }
    const scheme = s.rows[0];
    if (scheme.status !== 'active') { await client.query('ROLLBACK'); return res.status(400).json({ error: `Scheme is ${scheme.status}` }); }
    const strata = scheme.strata || [];
    const st = stratum || '';
    if (strata.length > 0 && !strata.includes(st)) {
      await client.query('ROLLBACK');
      return res.status(400).json({ error: `stratum must be one of: ${strata.join(', ')}` });
    }
    const dup = await client.query(
      'SELECT 1 FROM randomization_assignments WHERE scheme=$1 AND subject_id=$2', [scheme.scheme_id, subject_id]);
    if (dup.rows.length > 0) { await client.query('ROLLBACK'); return res.status(409).json({ error: `Subject ${subject_id} already randomized in this scheme` }); }

    const cnt = await client.query(
      'SELECT COUNT(*)::int AS n FROM randomization_assignments WHERE scheme=$1 AND stratum=$2', [scheme.scheme_id, st]);
    const pos = cnt.rows[0].n;                       // 0-based position within stratum
    const block = permutedBlock(scheme, st, Math.floor(pos / scheme.block_size));
    const arm = block[pos % scheme.block_size];

    const ins = await client.query(
      `INSERT INTO randomization_assignments (scheme, subject_id, stratum, arm, block_no, position, assigned_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,
      [scheme.scheme_id, subject_id, st, arm, Math.floor(pos / scheme.block_size), pos % scheme.block_size, req.user?.email || null]
    );
    await client.query('COMMIT');
    res.status(201).json(ins.rows[0]);
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    res.status(500).json({ error: err.message });
  } finally { client.release(); }
});

randomizationRouter.post('/irt/dispense', async (req, res) => {
  const client = await pool.connect();
  try {
    const { scheme_id, subject_id, site, assigned_by, notes } = req.body || {};
    if (!scheme_id || !subject_id) return res.status(400).json({ error: 'scheme_id and subject_id are required' });
    await client.query('BEGIN');
    const a = await client.query(
      `SELECT a.*, s.trial FROM randomization_assignments a
       JOIN randomization_schemes s ON s.scheme_id=a.scheme
       WHERE a.scheme=$1 AND a.subject_id=$2
       FOR UPDATE`,
      [scheme_id, subject_id]
    );
    if (a.rows.length === 0) {
      await client.query('ROLLBACK');
      return res.status(404).json({ error: `No randomization assignment found for ${subject_id} in ${scheme_id}` });
    }
    const assignment = a.rows[0];
    const existing = await client.query('SELECT * FROM irt_dispenses WHERE scheme=$1 AND subject_id=$2', [scheme_id, subject_id]);
    if (existing.rows.length > 0) {
      await client.query('ROLLBACK');
      return res.status(409).json({ error: 'Subject already has an IRT dispense record', dispense: existing.rows[0] });
    }
    const kit = await client.query(
      `SELECT * FROM irt_kits
       WHERE trial=$1 AND arm=$2 AND status='available'
         AND ($3::text IS NULL OR site=$3)
       ORDER BY expiry_date ASC NULLS LAST, kit_id ASC
       LIMIT 1 FOR UPDATE`,
      [assignment.trial, assignment.arm, site || null]
    );
    if (kit.rows.length === 0) {
      await client.query('ROLLBACK');
      return res.status(409).json({ error: `No available kit for trial ${assignment.trial}, arm ${assignment.arm}${site ? `, site ${site}` : ''}` });
    }
    const selectedKit = kit.rows[0];
    await client.query(
      `UPDATE irt_kits
       SET status='assigned', assigned_subject=$1, assigned_at=NOW(), updated_at=NOW()
       WHERE id=$2`,
      [subject_id, selectedKit.id]
    );
    const dispenseId = `DSP-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`;
    const d = await client.query(
      `INSERT INTO irt_dispenses (dispense_id, scheme, trial, subject_id, arm, kit_id, site, dispensed_by, notes)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
      [dispenseId, scheme_id, assignment.trial, subject_id, assignment.arm, selectedKit.kit_id, selectedKit.site, assigned_by || req.user?.email || null, notes || null]
    );
    await client.query('COMMIT');
    res.status(201).json({ assignment, kit: { ...selectedKit, status: 'assigned', assigned_subject: subject_id }, dispense: d.rows[0] });
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

/* ============================================================
   ROUTER 2 — SDTM-shaped export  (/api/sdtm)
   SDTM-SHAPED, not CDISC-conformance-validated. USUBJID uses the
   convention <STUDYID>-<SUBJID>.
   ============================================================ */
const sdtmRouter = express.Router();

const SDTM_DOMAINS = {
  DM: { label: 'Demographics',      source: 'patients' },
  AE: { label: 'Adverse Events',    source: 'adverse_events' },
  DV: { label: 'Protocol Deviations', source: 'deviations' },
};

sdtmRouter.get('/domains', (req, res) => {
  res.json(Object.entries(SDTM_DOMAINS).map(([code, d]) => ({ domain: code, ...d })));
});

async function sdtmRows(domain, trial) {
  const where = trial ? ' WHERE trial = $1' : '';
  const params = trial ? [trial] : [];
  if (domain === 'DM') {
    const r = await pool.query(`SELECT * FROM patients${where} ORDER BY trial, patient_id`, params);
    return r.rows.map((p, i) => ({
      STUDYID: p.trial, DOMAIN: 'DM',
      USUBJID: `${p.trial}-${p.patient_id}`, SUBJID: p.patient_id,
      SITEID: p.site, ARM: p.arm || '', ARMCD: (p.arm || '').replace(/[^A-Za-z0-9]/g, '').slice(0, 8).toUpperCase(),
      RFSTDTC: p.enrolled_at ? String(p.enrolled_at.toISOString()).slice(0, 10) : '',
      DMSEQ: i + 1,
    }));
  }
  if (domain === 'AE') {
    const r = await pool.query(`SELECT * FROM adverse_events${where} ORDER BY trial, event_id`, params);
    return r.rows.map((a, i) => ({
      STUDYID: a.trial, DOMAIN: 'AE',
      USUBJID: `${a.trial}-${a.patient}`, AESEQ: i + 1,
      AETERM: a.term, AESEV: (a.severity || '').toUpperCase(),
      AESER: a.serious ? 'Y' : 'N',
      AESTDTC: a.reported_at ? String(a.reported_at.toISOString()).slice(0, 10) : '',
      AEOUT: (a.outcome || '').toUpperCase(),
    }));
  }
  if (domain === 'DV') {
    const r = await pool.query(`SELECT * FROM deviations${where} ORDER BY trial, deviation_id`, params);
    return r.rows.map((d, i) => ({
      STUDYID: d.trial, DOMAIN: 'DV',
      USUBJID: `${d.trial}-SITE:${d.site}`, DVSEQ: i + 1,
      DVTERM: d.description || '', DVCAT: (d.type || '').toUpperCase(),
      DVSTATUS: (d.status || '').toUpperCase(),
    }));
  }
  throw new Error(`Unsupported domain ${domain}`);
}

sdtmRouter.get('/:domain', async (req, res) => {
  try {
    const domain = String(req.params.domain || '').toUpperCase();
    if (!SDTM_DOMAINS[domain]) return res.status(404).json({ error: `Unknown domain ${domain}. Supported: ${Object.keys(SDTM_DOMAINS).join(', ')}` });
    const rows = await sdtmRows(domain, req.query.trial || null);
    if ((req.query.format || '').toLowerCase() === 'csv') {
      const cols = rows.length ? Object.keys(rows[0]) : [];
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="${domain}.csv"`);
      return res.send(toCsv(rows, cols));
    }
    res.json({ domain, sdtm_shaped: true, cdisc_validated: false, count: rows.length, rows });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTER 3 — DSMB packet generator  (/api/dsmb)
   Deterministic aggregation + ADVISORY-ONLY AI executive summary.
   ============================================================ */
const dsmbRouter = express.Router();

dsmbRouter.post('/packet', async (req, res) => {
  try {
    const { trial } = req.body;
    if (!trial) return res.status(400).json({ error: 'trial is required' });
    const t = await pool.query('SELECT * FROM trials WHERE trial_id=$1', [trial]);
    if (t.rows.length === 0) return res.status(404).json({ error: `Trial ${trial} not found` });

    const [enrollBySite, enrollByArm, aeSeverity, aeSerious, deviations, queries, milestones] = await Promise.all([
      pool.query(`SELECT site, COUNT(*)::int AS n FROM patients WHERE trial=$1 GROUP BY site ORDER BY site`, [trial]),
      pool.query(`SELECT COALESCE(arm,'(unassigned)') AS arm, COUNT(*)::int AS n FROM patients WHERE trial=$1 GROUP BY arm ORDER BY arm`, [trial]),
      pool.query(`SELECT severity, COUNT(*)::int AS n FROM adverse_events WHERE trial=$1 GROUP BY severity`, [trial]),
      pool.query(`SELECT COUNT(*)::int AS n FROM adverse_events WHERE trial=$1 AND serious=TRUE`, [trial]),
      pool.query(`SELECT type, status, COUNT(*)::int AS n FROM deviations WHERE trial=$1 GROUP BY type, status`, [trial]),
      pool.query(`SELECT status, COUNT(*)::int AS n FROM queries WHERE trial=$1 GROUP BY status`, [trial]),
      pool.query(`SELECT milestone_id, name, target_date, actual_date, status FROM milestones WHERE trial=$1 ORDER BY target_date`, [trial]),
    ]);

    const packet = {
      trial: t.rows[0],
      generated_at: new Date().toISOString(),
      enrollment: { by_site: enrollBySite.rows, by_arm: enrollByArm.rows },
      safety: { ae_by_severity: aeSeverity.rows, serious_ae_count: aeSerious.rows[0].n },
      conduct: { deviations: deviations.rows, queries: queries.rows },
      milestones: milestones.rows,
    };

    // ADVISORY AI executive summary over the aggregates only (no PHI).
    let summary = null;
    try {
      const r = await callOpenRouter(
        SYSTEM_PROMPT,
        `Write a DSMB open-session executive summary for this trial data. Return STRICT JSON: {"summary": string, "signals": [string], "recommended_focus_areas": [string]}.\nDATA: ${JSON.stringify({ trial: packet.trial.trial_id, indication: packet.trial.indication, phase: packet.trial.phase, ...packet.enrollment, ...packet.safety, ...packet.conduct })}`
      );
      summary = safeJsonParse(r, { summary: typeof r === 'string' ? r : '' });
    } catch (e) { summary = { summary: '', error: `AI narrative unavailable: ${e.message}` }; }

    const out = withAdvisory({ packet, executive_summary: summary });
    await persist('dsmb-packet', req.body, out);
    res.json(out);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTER 4 — Enrollment forecast  (/api/enrollment-forecast)
   Deterministic accrual projection from patients.enrolled_at,
   plus ADVISORY AI narrative.
   ============================================================ */
const forecastRouter = express.Router();

forecastRouter.post('/run', async (req, res) => {
  try {
    const { trial, target_n } = req.body;
    if (!trial) return res.status(400).json({ error: 'trial is required' });
    const target = Number(target_n) || 0;

    const r = await pool.query(
      `SELECT date_trunc('month', enrolled_at) AS month, COUNT(*)::int AS n
       FROM patients WHERE trial=$1 AND enrolled_at IS NOT NULL
       GROUP BY 1 ORDER BY 1`, [trial]);
    const monthly = r.rows.map(x => ({ month: String(x.month.toISOString()).slice(0, 7), n: x.n }));
    const enrolled = monthly.reduce((s, m) => s + m.n, 0);

    // Rate = mean of the most recent 3 accrual months (or all, if fewer).
    const recent = monthly.slice(-3);
    const rate = recent.length ? recent.reduce((s, m) => s + m.n, 0) / recent.length : 0;
    const remaining = Math.max(0, target - enrolled);
    const monthsToTarget = rate > 0 && remaining > 0 ? Math.ceil(remaining / rate) : (remaining === 0 ? 0 : null);

    const projection = {
      trial, enrolled, target_n: target || null,
      monthly_accrual: monthly,
      recent_rate_per_month: Number(rate.toFixed(2)),
      remaining, months_to_target: monthsToTarget,
      projected_completion: monthsToTarget !== null && target
        ? new Date(Date.now() + monthsToTarget * 30.44 * 24 * 3600 * 1000).toISOString().slice(0, 10)
        : null,
      method: 'mean of last 3 accrual months, linear projection',
    };

    let narrative = null;
    try {
      const ai = await callOpenRouter(
        SYSTEM_PROMPT,
        `Given this enrollment projection, return STRICT JSON {"narrative": string, "risks": [string], "accelerators": [string]}.\nDATA: ${JSON.stringify(projection)}`
      );
      narrative = safeJsonParse(ai, { narrative: typeof ai === 'string' ? ai : '' });
    } catch (e) { narrative = { narrative: '', error: `AI narrative unavailable: ${e.message}` }; }

    const out = withAdvisory({ projection, narrative });
    await persist('enrollment-forecast', req.body, out);
    res.json(out);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTER 5 — extra AI verbs  (mounted at /api/ai)
   ============================================================ */
const aiRouter = express.Router();

/* MedDRA-style coding assistant — ADVISORY ONLY. We do NOT ship the
   licensed MedDRA dictionary; the model proposes SOC/PT-style terms that
   MUST be verified against a licensed MedDRA browser by a coder. */
aiRouter.post('/meddra-code', async (req, res) => {
  try {
    const { terms } = req.body;
    const list = Array.isArray(terms) ? terms : String(terms || '').split('\n').map(s => s.trim()).filter(Boolean);
    if (list.length === 0) return res.status(400).json({ error: 'terms is required (array or newline-separated string)' });
    const r = await callOpenRouter(
      SYSTEM_PROMPT,
      `Propose MedDRA-style coding for these verbatim adverse-event terms. Return STRICT JSON: {"codings": [{"verbatim": string, "proposed_pt": string, "proposed_soc": string, "confidence": "high"|"medium"|"low", "note": string}]}.\nTERMS: ${JSON.stringify(list)}`
    );
    const out = withAdvisory({
      not_licensed_meddra: true,
      note: 'Proposed terms are model output, NOT from a licensed MedDRA dictionary. A certified coder must verify every code.',
      ...safeJsonParse(r, { codings: [] }),
    });
    await persist('meddra-code', { terms: list }, out);
    res.json(out);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* Safety narrative generator — ADVISORY ONLY. Drafts a CIOMS-style
   narrative from an adverse_events row (or ad-hoc fields). */
aiRouter.post('/safety-narrative', async (req, res) => {
  try {
    let ae = req.body.event || null;
    if (!ae && req.body.event_id) {
      const r = await pool.query('SELECT * FROM adverse_events WHERE event_id=$1', [req.body.event_id]);
      if (r.rows.length === 0) return res.status(404).json({ error: `Adverse event ${req.body.event_id} not found` });
      ae = r.rows[0];
    }
    if (!ae) return res.status(400).json({ error: 'Provide event_id or an event object' });
    const r = await callOpenRouter(
      SYSTEM_PROMPT,
      `Draft a CIOMS-style safety narrative for this adverse event. Return STRICT JSON: {"narrative": string, "missing_information": [string], "queries_to_raise": [string]}.\nEVENT: ${JSON.stringify(ae)}`
    );
    const out = withAdvisory(safeJsonParse(r, { narrative: '' }));
    await persist('safety-narrative', { event: ae }, out);
    res.json(out);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTER 6 — Form FDA 1572 generator  (/api/form-1572)
   Deterministic DRAFT assembly from existing records. Marked DRAFT:
   a real 1572 requires wet/e-signature and regulatory review.
   ============================================================ */
const form1572Router = express.Router();

form1572Router.post('/generate', async (req, res) => {
  try {
    const { investigator_id, trial } = req.body;
    if (!investigator_id) return res.status(400).json({ error: 'investigator_id is required' });
    const inv = await pool.query('SELECT * FROM investigators WHERE investigator_id=$1', [investigator_id]);
    if (inv.rows.length === 0) return res.status(404).json({ error: `Investigator ${investigator_id} not found` });
    const investigator = inv.rows[0];

    const site = investigator.site
      ? (await pool.query('SELECT * FROM sites WHERE site_id=$1', [investigator.site])).rows[0] || null
      : null;
    const trialRow = trial
      ? (await pool.query('SELECT * FROM trials WHERE trial_id=$1', [trial])).rows[0] || null
      : null;
    const subInvestigators = investigator.site
      ? (await pool.query(
          `SELECT entry_id, staff_name, staff_role, delegated_tasks FROM delegation_log_entries
           WHERE site=$1 AND status='active' ORDER BY staff_name`, [investigator.site])).rows
      : [];

    res.json({
      form: 'FDA-1572 (Statement of Investigator)',
      status: 'DRAFT — requires investigator signature and regulatory review before use',
      generated_at: new Date().toISOString(),
      section_1_investigator: {
        name: investigator.name,
        title: investigator.title,
        specialty: investigator.specialty,
        certifications: investigator.certifications,
      },
      section_2_education: 'Attach curriculum vitae (CV) — not stored in this system',
      section_3_facility: site ? { site_id: site.site_id, name: site.name, city: site.city, country: site.country } : null,
      section_4_clinical_lab: 'Attach laboratory certifications (CLIA/CAP) — not stored in this system',
      section_5_irb: 'See IRB workflow records for this site (/irb-workflows)',
      section_6_sub_investigators: subInvestigators,
      section_7_protocol: trialRow ? { trial_id: trialRow.trial_id, name: trialRow.name, phase: trialRow.phase, sponsor: trialRow.sponsor } : null,
      section_8_commitments: 'Standard Form 1572 commitments text applies (21 CFR 312.53).',
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTERS 7 & 8 — Delegation log + Training records (CRUD)
   Same response shapes as the other CRUD modules (bare array on
   list, row objects elsewhere) so CrudTable just works.
   ============================================================ */
function crudRouter(table, idField, columns) {
  const router = express.Router();
  router.get('/', async (req, res) => {
    try {
      const r = await pool.query(`SELECT * FROM ${table} ORDER BY id DESC`);
      res.json(r.rows);
    } catch (err) { res.status(500).json({ error: err.message }); }
  });
  router.post('/', async (req, res) => {
    try {
      const vals = columns.map(c => req.body[c] ?? null);
      const params = columns.map((_, i) => `$${i + 1}`).join(',');
      const r = await pool.query(
        `INSERT INTO ${table} (${columns.join(',')}) VALUES (${params}) RETURNING *`, vals);
      res.status(201).json(r.rows[0]);
    } catch (err) { res.status(500).json({ error: err.message }); }
  });
  router.put('/:id', async (req, res) => {
    try {
      const sets = columns.map((c, i) => `${c}=$${i + 1}`).join(', ');
      const vals = columns.map(c => req.body[c] ?? null);
      const r = await pool.query(
        `UPDATE ${table} SET ${sets}, updated_at=NOW() WHERE id=$${columns.length + 1} RETURNING *`,
        [...vals, req.params.id]);
      if (r.rows.length === 0) return res.status(404).json({ error: 'Not found' });
      res.json(r.rows[0]);
    } catch (err) { res.status(500).json({ error: err.message }); }
  });
  router.delete('/:id', async (req, res) => {
    try {
      const r = await pool.query(`DELETE FROM ${table} WHERE id=$1 RETURNING id`, [req.params.id]);
      if (r.rows.length === 0) return res.status(404).json({ error: 'Not found' });
      res.json({ deleted: true });
    } catch (err) { res.status(500).json({ error: err.message }); }
  });
  return router;
}

const delegationRouter = crudRouter('delegation_log_entries', 'entry_id',
  ['entry_id', 'trial', 'site', 'staff_name', 'staff_role', 'delegated_tasks', 'delegated_by', 'effective_from', 'effective_to', 'status']);

const trainingRouter = crudRouter('training_records', 'record_id',
  ['record_id', 'trial', 'site', 'staff_name', 'course', 'course_type', 'completed_at', 'expires_at', 'status']);

module.exports = {
  randomizationRouter,
  sdtmRouter,
  dsmbRouter,
  forecastRouter,
  aiRouter,
  form1572Router,
  delegationRouter,
  trainingRouter,
  // exposed for the seeder so seeded assignments are derived with the SAME
  // algorithm the API uses (keeps the "reproducible from seed" story true)
  permutedBlock,
};
