/* ============================================================
   Pass 7 — full backlog implementation
   ------------------------------------------------------------
   This module exports MULTIPLE Express routers, each mounted
   at a distinct base path in server.js. Grouped here so the
   whole pass-7 surface lives in one auditable file.

   Categories:
     1. MECHANICAL          — deterministic compute + optional AI narrative
     2. NEEDS-PRODUCT-DECISION — protocol version-graph + IRB state-machine
     3. TOO-RISKY (ADVISORY ONLY) — every response carries `disclaimer`,
        `requires_expert_review: true`, `not_for_regulatory_submission: true`
     4. NEEDS-CREDS (503 stubs) — known-shape endpoints that return
        503 + machine-readable `required_credentials`

   Persistence: every AI POST writes to ai_results(feature,input,output,model)
   so it shows up in the existing /ai/history UI.
   ============================================================ */

const express = require('express');
const pool = require('../config/database');
const { callOpenRouter, safeJsonParse } = require('../services/ai');

const MODEL = process.env.OPENROUTER_MODEL || 'anthropic/claude-haiku-4.5';
const SYSTEM_PROMPT = 'You are an expert clinical trial methodologist, biostatistician, and pharmaceutical R&D advisor. Provide rigorous, evidence-based, regulator-aware recommendations grounded in ICH-GCP, FDA, and EMA guidance. Always return STRICT JSON when a schema is given.';

const ADVISORY_DISCLAIMER =
  'ADVISORY OUTPUT ONLY. This response is generated by a language model and is NOT validated for regulatory submission, ' +
  'patient-care decisions, or go/no-go program decisions. It MUST be independently reviewed by a qualified biostatistician, ' +
  'medical monitor, regulatory affairs professional, or other domain expert before any operational use.';

function withAdvisory(obj) {
  return {
    disclaimer: ADVISORY_DISCLAIMER,
    requires_expert_review: true,
    not_for_regulatory_submission: true,
    ...obj,
  };
}

async function persist(feature, input, output) {
  try {
    await pool.query(
      'INSERT INTO ai_results (feature, input, output, model) VALUES ($1,$2,$3,$4)',
      [feature, input, output, MODEL]
    );
  } catch (e) {
    console.warn('[ai_results] persist warning:', e.message);
  }
}

/* ============================================================
   ROUTER 1 — extra AI endpoints (mounted at /api/ai)
   These extend the existing /api/ai surface without modifying
   routes/ai.js.
   ============================================================ */
const aiRouter = express.Router();

/* ---------- MECHANICAL: power-calc explainer ---------- */
/* Deterministic: explain assumptions (alpha, beta, MDE, SD, allocation).
   We do NOT pretend to be a power-analysis package — we surface the
   walk-through and an n-per-arm estimate using a textbook normal-approx
   formula so the explanation has a concrete number. */
function zForAlpha(alpha, twoSided = true) {
  // crude inverse normal — covers common 0.05/0.025/0.01/0.005 cases
  const a = twoSided ? alpha / 2 : alpha;
  if (a <= 0.0005) return 3.291;
  if (a <= 0.001)  return 3.090;
  if (a <= 0.005)  return 2.576;
  if (a <= 0.01)   return 2.326;
  if (a <= 0.025)  return 1.960;
  if (a <= 0.05)   return 1.645;
  return 1.282;
}
function zForPower(power) {
  if (power >= 0.99) return 2.326;
  if (power >= 0.95) return 1.645;
  if (power >= 0.9)  return 1.282;
  if (power >= 0.85) return 1.036;
  if (power >= 0.8)  return 0.842;
  if (power >= 0.7)  return 0.524;
  return 0.253;
}
aiRouter.post('/power-calc-explain', async (req, res) => {
  try {
    const body = req.body || {};
    const alpha = Number(body.alpha) || 0.05;
    const power = Number(body.power) || 0.8;
    const sd = Number(body.sd) || 1.0;
    const mde = Number(body.mde) || 0.5;
    const dropout = Number(body.dropout_rate) || 0.15;
    const twoSided = body.two_sided !== false;

    const za = zForAlpha(alpha, twoSided);
    const zb = zForPower(power);
    // continuous outcome, two-arm 1:1, normal approx
    const nPerArmEvaluable = Math.ceil(2 * Math.pow((za + zb) * sd / mde, 2));
    const nPerArmEnrolled = Math.ceil(nPerArmEvaluable / Math.max(0.05, 1 - dropout));
    const totalN = nPerArmEnrolled * 2;

    const deterministic = {
      inputs: { alpha, power, sd, mde, dropout_rate: dropout, two_sided: twoSided },
      derived: {
        z_alpha: Number(za.toFixed(3)),
        z_beta: Number(zb.toFixed(3)),
        n_per_arm_evaluable: nPerArmEvaluable,
        n_per_arm_enrolled: nPerArmEnrolled,
        total_n_enrolled: totalN,
      },
      formula: 'n_per_arm = 2 * ((z_{alpha/2} + z_{beta}) * SD / MDE)^2 (continuous outcome, two-arm 1:1, normal approximation)',
      assumptions_walkthrough: [
        `Significance level (alpha): ${alpha}${twoSided ? ' two-sided' : ' one-sided'} -> z_alpha = ${za.toFixed(3)}`,
        `Target power (1 - beta): ${power} -> z_beta = ${zb.toFixed(3)}`,
        `Pooled SD on the primary endpoint scale: ${sd}`,
        `Minimum detectable effect (MDE) on the primary endpoint scale: ${mde}`,
        `Drop-out inflation: ${(dropout * 100).toFixed(0)}% -> enrolled n_per_arm = ceil(evaluable / (1 - dropout))`,
        '1:1 allocation between treatment and control assumed. For unequal allocation, multiply by (1 + 1/k)/2 with k = ratio.',
      ],
      caveats: [
        'This is a normal-approximation estimate for a continuous outcome. It is NOT a substitute for a biostatistician-validated power analysis package (e.g. PASS, nQuery, EAST, SAS PROC POWER).',
        'For survival, count, time-to-event, non-inferiority, or group-sequential designs, the formula above does not apply and a specialist tool MUST be used.',
        'Effect size assumptions should be defended with literature or a pilot dataset before being used in a protocol.',
      ],
    };

    let narrative = null;
    try {
      const sys = `${SYSTEM_PROMPT} Return JSON: { "narrative": string, "key_caveats": [string] }. Focus on EXPLAINING the inputs and the resulting n; do NOT invent numbers.`;
      const user = `Explain the assumptions and resulting sample size below to a non-statistician trial sponsor. Be concrete; reference each input.
Deterministic calc result: ${JSON.stringify(deterministic)}`;
      const r = await callOpenRouter(sys, user);
      narrative = safeJsonParse(r, { narrative: typeof r === 'string' ? r : '', key_caveats: [] });
    } catch (e) {
      narrative = { narrative: '(AI narrative unavailable: ' + e.message + ')', key_caveats: [] };
    }

    const result = { ...deterministic, ai_narrative: narrative };
    await persist('power-calc-explain', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- MECHANICAL: patient burden estimator ---------- */
/* Pure structured calc + optional AI narrative.
   Inputs: visits[{name, procedures[{name, minutes}], travel_minutes}].
   Output: total minutes, hours, day-count, intensity tag, plus narrative. */
aiRouter.post('/patient-burden', async (req, res) => {
  try {
    const body = req.body || {};
    const visits = Array.isArray(body.visits) ? body.visits : [];
    let totalProcedureMin = 0;
    let totalTravelMin = 0;
    let totalProcedures = 0;
    const perVisit = visits.map((v, idx) => {
      const procs = Array.isArray(v.procedures) ? v.procedures : [];
      const procMin = procs.reduce((s, p) => s + (Number(p.minutes) || 0), 0);
      const travelMin = (Number(v.travel_minutes) || 0) * 2; // round trip
      totalProcedureMin += procMin;
      totalTravelMin += travelMin;
      totalProcedures += procs.length;
      return {
        index: idx,
        name: v.name || `Visit ${idx + 1}`,
        procedure_count: procs.length,
        procedure_minutes: procMin,
        travel_minutes_round_trip: travelMin,
        total_minutes: procMin + travelMin,
      };
    });

    const totalMin = totalProcedureMin + totalTravelMin;
    const totalHours = +(totalMin / 60).toFixed(2);
    const equivalentFullDays = +(totalMin / 480).toFixed(2); // 8-hour days
    let intensity = 'Low';
    if (totalHours > 80) intensity = 'Very High';
    else if (totalHours > 40) intensity = 'High';
    else if (totalHours > 16) intensity = 'Moderate';

    const deterministic = {
      visit_count: visits.length,
      total_procedure_count: totalProcedures,
      total_procedure_minutes: totalProcedureMin,
      total_travel_minutes: totalTravelMin,
      total_minutes: totalMin,
      total_hours: totalHours,
      equivalent_full_8h_days: equivalentFullDays,
      intensity_tag: intensity,
      per_visit: perVisit,
    };

    let narrative = null;
    try {
      const sys = `${SYSTEM_PROMPT} Return JSON: { "patient_facing_summary": string, "burden_reduction_suggestions": [string] }. Plain language, no PHI, no medical advice.`;
      const user = `Summarise patient burden for this trial schedule (one paragraph, plain language) and suggest 3-5 burden-reduction ideas (decentralised visits, home health, telehealth, combined procedure days). Use ONLY the numbers below.
${JSON.stringify(deterministic)}`;
      const r = await callOpenRouter(sys, user);
      narrative = safeJsonParse(r, { patient_facing_summary: typeof r === 'string' ? r : '', burden_reduction_suggestions: [] });
    } catch (e) {
      narrative = { patient_facing_summary: '(AI narrative unavailable: ' + e.message + ')', burden_reduction_suggestions: [] };
    }

    const result = { ...deterministic, ai_narrative: narrative };
    await persist('patient-burden', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- TOO-RISKY (ADVISORY ONLY): I/E criteria optimizer ---------- */
aiRouter.post('/ie-optimizer', async (req, res) => {
  try {
    const body = req.body || {};
    const sys = `${SYSTEM_PROMPT} Return STRICT JSON:
{
  "inclusion_suggestions": [{ "criterion": string, "rationale": string, "funnel_impact": string }],
  "exclusion_suggestions": [{ "criterion": string, "rationale": string, "safety_signal": string }],
  "criteria_to_consider_removing": [{ "criterion": string, "reason": string }],
  "estimated_screen_fail_reduction_pct": number,
  "evidence_basis": [string],
  "summary": string
}`;
    const user = `Suggest optimisations to inclusion/exclusion criteria for this trial. Output is ADVISORY ONLY. Indication / phase / current criteria:
${JSON.stringify(body, null, 2)}`;
    const r = await callOpenRouter(sys, user);
    const parsed = safeJsonParse(r, { summary: typeof r === 'string' ? r : '', inclusion_suggestions: [] });
    const result = withAdvisory(parsed);
    await persist('ie-optimizer', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- TOO-RISKY (ADVISORY ONLY): IND/NDA section drafter ---------- */
aiRouter.post('/ind-nda-section', async (req, res) => {
  try {
    const body = req.body || {};
    const section = body.section || 'Module 2.5 Clinical Overview';
    const sys = `${SYSTEM_PROMPT} Return STRICT JSON:
{
  "section_title": string,
  "outline": [{ "heading": string, "guidance": string, "draft_paragraph": string }],
  "cross_references_required": [string],
  "ich_module_mapping": string,
  "open_questions_for_regulatory_affairs": [string],
  "summary": string
}`;
    const user = `Draft a high-level OUTLINE for an IND/NDA section. Output is ADVISORY ONLY and must be reviewed by Regulatory Affairs before any submission use.
Requested section: ${section}
Context: ${JSON.stringify(body, null, 2)}`;
    const r = await callOpenRouter(sys, user);
    const parsed = safeJsonParse(r, { section_title: section, summary: typeof r === 'string' ? r : '' });
    const result = withAdvisory(parsed);
    await persist('ind-nda-section', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- TOO-RISKY (ADVISORY ONLY): dropout predictor ---------- */
aiRouter.post('/dropout-predictor', async (req, res) => {
  try {
    const body = req.body || {};
    const sys = `${SYSTEM_PROMPT} Return STRICT JSON:
{
  "predicted_dropout_rate_pct": number,
  "confidence_interval_pct": { "low": number, "high": number },
  "drivers": [{ "factor": string, "direction": "Increases" | "Decreases", "magnitude": "Small" | "Moderate" | "Large" }],
  "retention_recommendations": [string],
  "limitations": [string],
  "summary": string
}`;
    const user = `Predict dropout rate for this trial design. Output is ADVISORY ONLY. Not for go/no-go decisions.
${JSON.stringify(body, null, 2)}`;
    const r = await callOpenRouter(sys, user);
    const parsed = safeJsonParse(r, { predicted_dropout_rate_pct: 0, summary: typeof r === 'string' ? r : '' });
    const result = withAdvisory(parsed);
    await persist('dropout-predictor', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- TOO-RISKY (ADVISORY ONLY): adaptive-design simulator ---------- */
aiRouter.post('/adaptive-sim', async (req, res) => {
  try {
    const body = req.body || {};
    const sys = `${SYSTEM_PROMPT} Return STRICT JSON:
{
  "design_type": string,
  "interim_analyses": [{ "fraction": number, "rule": string, "expected_action": string }],
  "type_1_error_control_strategy": string,
  "operating_characteristics_qualitative": { "power": string, "expected_n": string, "expected_duration": string },
  "biostat_validation_required": [string],
  "summary": string
}`;
    const user = `Describe an adaptive design (Bayesian, group-sequential, or sample-size re-estimation) for this trial. Output is QUALITATIVE ADVISORY ONLY — does not produce operating characteristics and is not a substitute for an EAST/FACTS/R simulation that a biostatistician owns.
${JSON.stringify(body, null, 2)}`;
    const r = await callOpenRouter(sys, user);
    const parsed = safeJsonParse(r, { summary: typeof r === 'string' ? r : '', design_type: 'unspecified' });
    const result = withAdvisory(parsed);
    await persist('adaptive-sim', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ---------- TOO-RISKY (ADVISORY ONLY): RWE external-control-arm matcher ---------- */
aiRouter.post('/rwe-match', async (req, res) => {
  try {
    const body = req.body || {};
    const sys = `${SYSTEM_PROMPT} Return STRICT JSON:
{
  "candidate_data_sources": [{ "source": string, "fit_rationale": string, "access_path": string }],
  "matching_strategy": string,
  "covariates_to_match_on": [string],
  "bias_concerns": [string],
  "regulatory_precedent_examples": [string],
  "summary": string
}`;
    const user = `Suggest external-control-arm / RWE matching strategy. Output is ADVISORY ONLY. Real implementation requires data-partner contracts (Flatiron, Optum, TriNetX, HealthVerity, claims, EHR) and HEOR sign-off.
${JSON.stringify(body, null, 2)}`;
    const r = await callOpenRouter(sys, user);
    const parsed = safeJsonParse(r, { summary: typeof r === 'string' ? r : '', candidate_data_sources: [] });
    const result = withAdvisory(parsed);
    await persist('rwe-match', body, result);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ============================================================
   ROUTER 2 — comparable trial finder (DB-side, MECHANICAL)
   Mounted at /api/comparable-trials
   ============================================================ */
const comparableRouter = express.Router();

comparableRouter.post('/find', async (req, res) => {
  try {
    const body = req.body || {};
    const indication = (body.indication || '').trim();
    const phase = (body.phase || '').trim();
    const limit = Math.min(50, Math.max(1, parseInt(body.limit) || 10));

    if (!indication && !phase) {
      return res.status(400).json({ error: 'At least one of `indication` or `phase` is required.' });
    }

    // Tokenize the indication for a loose match — split on non-word chars, drop
    // very short tokens, and search for any token via ILIKE.
    const tokens = indication
      .split(/[^a-zA-Z0-9]+/)
      .map((t) => t.trim())
      .filter((t) => t.length >= 3);

    const where = [];
    const params = [];
    let i = 1;
    if (tokens.length > 0) {
      const ors = tokens.map(() => `indication ILIKE $${i++}`);
      where.push('(' + ors.join(' OR ') + ')');
      tokens.forEach((t) => params.push('%' + t + '%'));
    }
    if (phase) {
      where.push(`phase ILIKE $${i++}`);
      params.push('%' + phase + '%');
    }
    const whereSql = where.length ? 'WHERE ' + where.join(' AND ') : '';

    const r = await pool.query(
      `SELECT trial_id, name, indication, phase, status, sponsor, start_date
         FROM trials
         ${whereSql}
         ORDER BY start_date DESC NULLS LAST
         LIMIT ${limit}`,
      params
    );

    // Rough similarity score: count how many tokens hit the indication, +1 if phase matches.
    const scored = r.rows.map((row) => {
      const ind = (row.indication || '').toLowerCase();
      const tokenHits = tokens.reduce((s, t) => s + (ind.includes(t.toLowerCase()) ? 1 : 0), 0);
      const phaseHit = phase && row.phase && row.phase.toLowerCase() === phase.toLowerCase() ? 1 : 0;
      const denom = Math.max(1, tokens.length + (phase ? 1 : 0));
      return {
        ...row,
        similarity_score: +((tokenHits + phaseHit) / denom).toFixed(3),
      };
    });
    scored.sort((a, b) => b.similarity_score - a.similarity_score);

    res.json({
      source: 'internal_trials_table',
      query: { indication, phase, tokens, limit },
      result_count: scored.length,
      results: scored,
      notes: [
        'Internal DB match only. ClinicalTrials.gov / EudraCT / CTIS / ICTRP search requires NEEDS-CREDS integration (see /api/integrations/ctgov/search).',
      ],
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ============================================================
   ROUTER 3 — protocol version-graph
   Mounted at /api/protocols-graph
   (Cannot mount at /api/protocols/* because protocols.js owns that
    prefix with a writeGate; this is a read-only view so we keep
    it separate and open to any authenticated user.)
   ============================================================ */
const protocolGraphRouter = express.Router();

protocolGraphRouter.get('/by-trial/:trialId', async (req, res) => {
  try {
    const trialId = req.params.trialId;
    const protocols = await pool.query(
      `SELECT id, protocol_id, trial, version, status, approved_by, approved_at, created_at, updated_at
         FROM protocols WHERE trial=$1 ORDER BY created_at ASC`,
      [trialId]
    );
    const amendments = await pool.query(
      `SELECT id, amendment_id, trial, version, summary, status, approved_at, created_at
         FROM amendments WHERE trial=$1 ORDER BY created_at ASC`,
      [trialId]
    );

    // Nodes: each protocol + each amendment.
    // Edges: protocols chained in version order; amendments attach to the
    // protocol whose version they reference (best-effort string match), else
    // to the most-recent protocol prior to the amendment's created_at.
    const nodes = [];
    protocols.rows.forEach((p) =>
      nodes.push({
        node_id: `P:${p.protocol_id}`,
        type: 'protocol',
        label: `${p.protocol_id} v${p.version || '?'}`,
        version: p.version,
        status: p.status,
        approved_at: p.approved_at,
        created_at: p.created_at,
      })
    );
    amendments.rows.forEach((a) =>
      nodes.push({
        node_id: `A:${a.amendment_id}`,
        type: 'amendment',
        label: `${a.amendment_id} v${a.version || '?'}`,
        version: a.version,
        status: a.status,
        approved_at: a.approved_at,
        created_at: a.created_at,
        summary: a.summary,
      })
    );

    const edges = [];
    for (let i = 1; i < protocols.rows.length; i++) {
      edges.push({
        from: `P:${protocols.rows[i - 1].protocol_id}`,
        to: `P:${protocols.rows[i].protocol_id}`,
        type: 'supersedes',
      });
    }
    amendments.rows.forEach((a) => {
      // try exact version match
      let parent = protocols.rows.find((p) => p.version && a.version && p.version === a.version);
      if (!parent) {
        // most-recent protocol before the amendment
        parent = [...protocols.rows]
          .filter((p) => new Date(p.created_at) <= new Date(a.created_at))
          .pop();
      }
      if (!parent && protocols.rows.length > 0) parent = protocols.rows[protocols.rows.length - 1];
      if (parent) {
        edges.push({
          from: `P:${parent.protocol_id}`,
          to: `A:${a.amendment_id}`,
          type: 'amended_by',
        });
      }
    });

    res.json({
      trial: trialId,
      node_count: nodes.length,
      edge_count: edges.length,
      nodes,
      edges,
      protocols: protocols.rows,
      amendments: amendments.rows,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Simple text-diff between two protocol versions (by protocol_id pair).
// We don't store the protocol body, so we diff metadata fields + any
// amendments whose version sits between v_from and v_to.
protocolGraphRouter.get('/diff', async (req, res) => {
  try {
    const fromId = req.query.from;
    const toId = req.query.to;
    if (!fromId || !toId) {
      return res.status(400).json({ error: 'Both `from` and `to` query params required (protocol_id values).' });
    }
    const r = await pool.query('SELECT * FROM protocols WHERE protocol_id IN ($1,$2)', [fromId, toId]);
    const fromRow = r.rows.find((p) => p.protocol_id === fromId);
    const toRow = r.rows.find((p) => p.protocol_id === toId);
    if (!fromRow || !toRow) return res.status(404).json({ error: 'One or both protocols not found' });

    const fields = ['trial', 'version', 'status', 'approved_by', 'approved_at'];
    const changes = fields
      .map((f) => ({ field: f, from: fromRow[f], to: toRow[f] }))
      .filter((c) => String(c.from) !== String(c.to));

    // Bracket amendments between the two protocol creation timestamps.
    const amendments = await pool.query(
      `SELECT amendment_id, version, summary, status, created_at FROM amendments
         WHERE trial=$1 AND created_at BETWEEN $2 AND $3 ORDER BY created_at ASC`,
      [fromRow.trial, fromRow.created_at, toRow.created_at]
    );

    res.json({
      from: fromRow,
      to: toRow,
      metadata_changes: changes,
      intervening_amendments: amendments.rows,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/* ============================================================
   ROUTER 4 — IRB state-machine
   Mounted at /api/irb-workflows
   States: draft -> submitted -> response_pending
                 -> approved | rejected -> continuing_review
   ============================================================ */
const irbRouter = express.Router();

const IRB_TRANSITIONS = {
  draft:              ['submitted'],
  submitted:          ['response_pending', 'approved', 'rejected'],
  response_pending:   ['approved', 'rejected', 'submitted'],
  approved:           ['continuing_review', 'rejected'],
  rejected:           ['draft'],
  continuing_review:  ['approved', 'rejected'],
};

irbRouter.get('/', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM irb_workflows ORDER BY id DESC LIMIT 200');
    res.json(r.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

irbRouter.get('/:id', async (req, res) => {
  try {
    const wf = await pool.query('SELECT * FROM irb_workflows WHERE id=$1', [req.params.id]);
    if (wf.rows.length === 0) return res.status(404).json({ error: 'Workflow not found' });
    const t = await pool.query(
      'SELECT * FROM irb_workflow_transitions WHERE workflow_id=$1 ORDER BY created_at ASC',
      [wf.rows[0].workflow_id]
    );
    res.json({
      workflow: wf.rows[0],
      transitions: t.rows,
      allowed_next_states: IRB_TRANSITIONS[wf.rows[0].state] || [],
      state_machine: IRB_TRANSITIONS,
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

irbRouter.post('/', async (req, res) => {
  try {
    const { workflow_id, trial, protocol, site, irb_name, expires_at, meta } = req.body || {};
    if (!workflow_id) return res.status(400).json({ error: 'workflow_id required' });
    const r = await pool.query(
      `INSERT INTO irb_workflows (workflow_id, trial, protocol, site, irb_name, state, expires_at, meta)
       VALUES ($1,$2,$3,$4,$5,'draft',$6,$7) RETURNING *`,
      [workflow_id, trial || null, protocol || null, site || null, irb_name || null, expires_at || null, meta || {}]
    );
    await pool.query(
      `INSERT INTO irb_workflow_transitions (workflow_id, from_state, to_state, actor, reason)
       VALUES ($1,NULL,'draft',$2,$3)`,
      [workflow_id, req.user?.email || 'system', 'workflow created']
    );
    res.status(201).json(r.rows[0]);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

irbRouter.post('/:id/transition', async (req, res) => {
  try {
    const { to_state, reason } = req.body || {};
    if (!to_state) return res.status(400).json({ error: '`to_state` required' });

    const wf = await pool.query('SELECT * FROM irb_workflows WHERE id=$1', [req.params.id]);
    if (wf.rows.length === 0) return res.status(404).json({ error: 'Workflow not found' });
    const current = wf.rows[0];
    const allowed = IRB_TRANSITIONS[current.state] || [];
    if (!allowed.includes(to_state)) {
      return res.status(400).json({
        error: `Illegal transition: ${current.state} -> ${to_state}. Allowed: ${allowed.join(', ') || '(terminal)'}.`,
      });
    }
    const stamp = to_state === 'approved' || to_state === 'continuing_review' ? 'NOW()' : null;
    const updated = await pool.query(
      `UPDATE irb_workflows
         SET state=$1, last_review_at=${stamp ? stamp : 'last_review_at'}, updated_at=NOW()
       WHERE id=$2 RETURNING *`,
      [to_state, req.params.id]
    );
    await pool.query(
      `INSERT INTO irb_workflow_transitions (workflow_id, from_state, to_state, actor, reason)
       VALUES ($1,$2,$3,$4,$5)`,
      [current.workflow_id, current.state, to_state, req.user?.email || 'system', reason || null]
    );
    res.json({ workflow: updated.rows[0], previous_state: current.state, new_state: to_state });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

/* ============================================================
   ROUTER 5 — NEEDS-CREDS integration stubs
   Mounted at /api/integrations
   Each endpoint responds 503 with a machine-readable shape so the
   frontend can render a "credentials required" UX.
   ============================================================ */
const integrationsRouter = express.Router();

function credStub(integration, requiredCredentials, extra) {
  return (req, res) =>
    res.status(503).json({
      integration,
      status: 'not_configured',
      reason: 'This integration requires credentials and/or a product decision before it can be enabled.',
      required_credentials: requiredCredentials,
      docs_url: null,
      ...(extra || {}),
    });
}

// ClinicalTrials.gov / NCT
integrationsRouter.get('/ctgov/search',
  credStub('clinicaltrials_gov', ['CTGOV_API_KEY (none — public API, but rate-limited)', 'CTGOV_PRS_USERNAME (for push)', 'CTGOV_PRS_PASSWORD (for push)'],
    { capability: 'search-by-indication/phase/endpoints; NCT push/pull; PRS-style validation' }));
integrationsRouter.post('/ctgov/push', credStub('clinicaltrials_gov_prs', ['CTGOV_PRS_USERNAME', 'CTGOV_PRS_PASSWORD']));
integrationsRouter.get('/ctgov/validate-prs', credStub('clinicaltrials_gov_prs', ['CTGOV_PRS_USERNAME', 'CTGOV_PRS_PASSWORD']));

// EudraCT
integrationsRouter.get('/eudract/search', credStub('eudract', ['EUDRACT_SPONSOR_USER', 'EUDRACT_SPONSOR_PASSWORD']));
integrationsRouter.post('/eudract/submit', credStub('eudract', ['EUDRACT_SPONSOR_USER', 'EUDRACT_SPONSOR_PASSWORD']));

// CTIS (EU Clinical Trials Information System)
integrationsRouter.get('/ctis/search', credStub('ctis', ['CTIS_OAUTH_CLIENT_ID', 'CTIS_OAUTH_CLIENT_SECRET', 'CTIS_SPONSOR_ORG_ID']));
integrationsRouter.post('/ctis/submit', credStub('ctis', ['CTIS_OAUTH_CLIENT_ID', 'CTIS_OAUTH_CLIENT_SECRET', 'CTIS_SPONSOR_ORG_ID']));

// FDA ESG (Electronic Submissions Gateway)
integrationsRouter.post('/fda-esg/submit', credStub('fda_esg', ['FDA_ESG_GATEWAY_USER', 'FDA_ESG_CLIENT_CERT_PATH', 'FDA_ESG_CLIENT_CERT_PASSPHRASE']));
integrationsRouter.get('/fda-esg/ack/:trackingId', credStub('fda_esg', ['FDA_ESG_GATEWAY_USER', 'FDA_ESG_CLIENT_CERT_PATH', 'FDA_ESG_CLIENT_CERT_PASSPHRASE']));

// EDC connectors (Medidata Rave, Veeva CDMS)
integrationsRouter.get('/edc/rave/studies', credStub('medidata_rave', ['RAVE_API_URL', 'RAVE_API_USER', 'RAVE_API_PASSWORD'], { product_decision: 'NEEDS-PRODUCT-DECISION on Part 11 audit-trail scope' }));
integrationsRouter.get('/edc/veeva/studies', credStub('veeva_cdms', ['VEEVA_VAULT_DNS', 'VEEVA_VAULT_USER', 'VEEVA_VAULT_PASSWORD'], { product_decision: 'NEEDS-PRODUCT-DECISION on Part 11 audit-trail scope' }));

// EHR connectors (generic FHIR)
integrationsRouter.get('/ehr/fhir/patients', credStub('ehr_fhir', ['EHR_FHIR_BASE_URL', 'EHR_FHIR_CLIENT_ID', 'EHR_FHIR_CLIENT_SECRET'], { product_decision: 'NEEDS-PRODUCT-DECISION on eConsent + Part 11' }));

// eConsent / 21 CFR Part 11 audit trails
integrationsRouter.get('/part11/audit-trail', credStub('part11_audit', ['(none — this is a PRODUCT scope decision, not a credential)'], { product_decision: 'NEEDS-PRODUCT-DECISION on 21 CFR Part 11 compliance scope (eConsent, esignature, audit retention).' }));

/* ============================================================
   Exports
   ============================================================ */
module.exports = {
  aiRouter,
  comparableRouter,
  protocolGraphRouter,
  irbRouter,
  integrationsRouter,
};
